### ISSUE TITLE
NoSuchMethodError thrown when starting espresso server and test app is using Compose 1.1.0

### ISSUE THREAD

**Issue by zpiao1** [appium/appium-espresso-driver#754]
Hi, recently Compose released a new version 1.1.0 and seems that actually introduced issues starting the Espresso Server.
## Behavior
Espresso Server fails to start

## Possible Reason
Seems that in Compose 1.1.0 new properties are added to the companion object of `androidx.compose.ui.node.ComposeUiNode`, which didn't exist in Compose 1.0.0. ([Source Here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/node/ComposeUiNode.kt;drc=d1bb6b866401d0c873b942fbfaab53289e88a174;l=47))  
Espresso Driver is still depending on 1.0.0 now so in runtime `NoSuchMethodError` will is thrown

## Possible Solution
Upgrading Compose version to 1.1.0 should solve the issue. However, this might require some other dependencies to be upgraded as well.

## Full Stacktrace
The stacktrace from espresso driver looks like this:
```
Process crashed while executing startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
java.lang.NoSuchMethodError: No virtual method getSetViewConfiguration()Lkotlin/jvm/functions/Function2; in class Landroidx/compose/ui/node/ComposeUiNode$Companion; or its super classes (declaration of 'androidx.compose.ui.node.ComposeUiNode$Companion' appears in /data/app/~~1_nq6rAkyElzumuVYtWifw==/io.appium.espressoserver.test-bYotccKJsakVDNsIY6psDA==/base.apk)
   at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:289)
   at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:255)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
   at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:252)
   at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:110)
   at <app.package.name>.ComposableSingletons$MainActivityKt$lambda-5$1.invoke(MainActivity.kt:52)
   at <app.package.name>.ComposableSingletons$MainActivityKt$lambda-5$1.invoke(MainActivity.kt:50)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:23)
   at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:82)
   at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:81)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
   at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:265)
   at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
   at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
   at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:72)
   at <app.package.name>.ui.theme.ThemeKt.AndroidComposeExampleTheme(Theme.kt:38)
   at <app.package.name>.ComposableSingletons$MainActivityKt$lambda-6$1.invoke(MainActivity.kt:50)
   at <app.package.name>.ComposableSingletons$MainActivityKt$lambda-6$1.invoke(MainActivity.kt:49)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:384)
   at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:228)
   at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:227)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
   at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:148)
   at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:114)
   at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:113)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
   at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:106)
   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:162)
   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:161)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:161)
   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:144)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3330)
   at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2577)
   at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2573)
   at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:540)
   at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2566)
   at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:2517)
   at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:476)
   at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:727)
   at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:432)
   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:144)
   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:135)
   at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:727)
   at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:135)
   at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:187)
   at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
   at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:135)
   at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:814)
   at android.view.View.dispatchAttachedToWindow(View.java:20753)
   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2613)
   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
   at android.view.Choreographer.doCallbacks(Choreographer.java:845)
   at android.view.Choreographer.doFrame(Choreographer.java:780)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
   at android.os.Handler.handleCallback(Handler.java:938)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loopOnce(Looper.java:201)
   at android.os.Looper.loop(Looper.java:288)
   at android.app.ActivityThread.main(ActivityThread.java:7839)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by mykola-mokhnach** [comment]
cc @rajdeepv

**Comment by rajdeepv** [comment]
Does changing compose to 1.1.0 fix your specific issue? If so, I could make it configurable through  capability

**Comment by zpiao1** [comment]
> Does changing compose to 1.1.0 fix your specific issue? If so, I could make it configurable through capability

Seems 1.1.0 also requires setting the compileSdk to be at least 31

**Comment by rajdeepv** [comment]
compileSdk can be configured using capability https://github.com/appium/appium-espresso-driver#espresso-build-config

**Comment by zpiao1** [comment]
> compileSdk can be configured using capability https://github.com/appium/appium-espresso-driver#espresso-build-config

Yes, thanks for pointing it out. I think making compose version configurable as well should solve the problem

**Comment by iparry7979** [comment]
How do we change compose version to 1.1.0 if it is not configurable via a capability? I am also having this issue but I'm unsure how to change the compose version.

**Comment by rajdeepv** [comment]
This is added in #760 

Make compose and Kotlin versions configurable by users using the espressoBuildConfig capability
`espressoBuildConfig:    '{"toolsVersions": {"composeVersion": "1.1.1", "compileSdk":"31", "kotlin":"1.6.10"}}',`

**Comment by rockstarrocks2020** [comment]
Still seeing this issue even after adding espressoBuildConfig: '{"toolsVersions": {"composeVersion": "1.1.1", "compileSdk":"31", "kotlin":"1.6.10"}}',

@[rajdeepv](https://github.com/rajdeepv) rajdeepv closed this [on 15 Mar](https://github.com/appium/appium-espresso-driver/issues/754#event-6239098679)

**Comment by iparry7979** [comment]
Have you rebuilt the Espresso driver? I usually do so after clearing the Gradle cache so I can be sure the rebuild is completely fresh. If you've done all that you'll probably need to provide more info such as stack trace so the guys can work it out.

**Comment by rockstarrocks2020** [comment]
Did gradle clean with the command -rm -r $HOME/.gradle/caches/ and ran the script still see the same issue


harechat_0a3e9cb90409.apk'
[debug] [ADB] Checking app cert for /var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_0a3e9cb90409.apk
[ADB] Using 'apksigner.jar' from '/Users/user/Library/Android/sdk/build-tools/33.0.0-rc2/lib/apksigner.jar'
[debug] [ADB] Starting apksigner: /Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Users/user/Library/Android/sdk/build-tools/33.0.0-rc2/lib/apksigner.jar verify --print-certs /var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_packagename_0a3e9cb90409.apk
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
[debug] [ADB] Signer #1 certificate SHA-256 digest: 002c64d93f0fb5bdeea80f971f70dcf51518e0f47f14b64059ee977d1b173b6f
[debug] [ADB] Signer #1 certificate SHA-1 digest: 511200a1536457787bff565ae1744c4fe34c6575
[debug] [ADB] Signer #1 certificate MD5 digest: 54b6022bd0922926162d853d4ec6aa29
[debug] [ADB] 
[ADB] '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_in.packagename_0a3e9cb90409.apk' is signed with a non-default certificate
[ADB] Using 'zipalign' from '/Users/user/Library/Android/sdk/build-tools/33.0.0-rc2/zipalign'
[debug] [ADB] /var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_packagename_0a3e9cb90409.apk' is already zip-aligned. Doing nothing
[debug] [ADB] Signing '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_in.package_0a3e9cb90409.apk' with default cert
[debug] [ADB] Starting apksigner: /Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Users/user/Library/Android/sdk/build-tools/33.0.0-rc2/lib/apksigner.jar sign --key /usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_in.package_0a3e9cb90409.apk
[debug] [ADB] Uninstalling io.appium.espressoserver.test
[debug] [ADB] Getting install status for io.appium.espressoserver.test
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell dumpsys package io.appium.espressoserver.test'
[debug] [ADB] 'io.appium.espressoserver.test' is installed
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell am force-stop io.appium.espressoserver.test'
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 uninstall io.appium.espressoserver.test'
[debug] [ADB] 'adb uninstall io.appium.espressoserver.test' command output: Success
[ADB] io.appium.espressoserver.test was successfully uninstalled
[Espresso] Uninstalled the obsolete Espresso server package from the device under test
[debug] [ADB] Getting install status for io.appium.espressoserver.test
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell dumpsys package io.appium.espressoserver.test'
[debug] [ADB] 'io.appium.espressoserver.test' is not installed
[debug] [ADB] App '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_in.package_0a3e9cb90409.apk' is not installed
[Espresso] Installing Espresso Test Server apk from the target device (path: '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_in.company_0a3e9cb90409.apk')
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 help'
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 features'
[ADB] The application at '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_in.package_0a3e9cb90409.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 install /var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_in.company.co.0a3e9cb90409.apk'
[ADB] The installation of 'io.appium.espressoserver.test_1.50.1_in.package_0a3e9cb90409.apk' took 39280ms
[debug] [ADB] Install command stdout: Serving...
[debug] [ADB] Performing Incremental Install
[debug] [ADB] 
[debug] [ADB] Exception occurred while executing 'install-incremental':
[debug] [ADB] java.lang.IllegalArgumentException: Incremental i...
[debug] [ADB] 	at android.os.Binder.execTransactInternal(Binder.java:1159)
[debug] [ADB] 	at android.os.Binder.execTransact(Binder.java:1123)
[debug] [ADB] Performing Streamed Install
[debug] [ADB] Success
[Espresso] Installed Espresso Test Server apk '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_1.50.1_in.companyt_0a3e9cb90409.apk' (pkg: 'io.appium.espressoserver.test')
[ADB] Adding packages ["io.appium.settings","io.appium.espressoserver.test"] to Doze whitelist
[debug] [ADB] Got the following command chunks to execute: [["dumpsys","deviceidle","whitelist","+io.appium.settings",";","dumpsys","deviceidle","whitelist","+io.appium.espressoserver.test",";"]]
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell dumpsys deviceidle whitelist +io.appium.settings ; dumpsys deviceidle whitelist +io.appium.espressoserver.test ;'
[debug] [Espresso] Performing cleanup of automation leftovers
[debug] [Espresso] No obsolete sessions have been detected (connect ECONNREFUSED ::1:8300)
[Espresso] Starting Espresso Server v1.50.1 with cmd: adb shell am instrument -w -e debug false -e disableAnalytics true io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","0a3e9cb90409","shell","am","instrument","-w","-e","debug",false,"-e","disableAnalytics",true,"io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
[Espresso] Waiting up to 1000000000ms for Espresso server to be online
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] connect ECONNREFUSED ::1:8300
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] connect ECONNREFUSED ::1:8300
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] connect ECONNREFUSED ::1:8300
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] connect ECONNREFUSED ::1:8300
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] connect ECONNREFUSED ::1:8300
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] connect ECONNREFUSED ::1:8300
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] connect ECONNREFUSED ::1:8300
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] connect ECONNREFUSED ::1:8300
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[debug] [Espresso] [Instrumentation] io.appium.espressoserver.EspressoServerRunnerTest:
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [WD Proxy] Got response with status 200: {"id":"4d9101c5-75ff-4cb3-8ffa-1957cb025e82","sessionId":null,"value":null}
[Espresso] Espresso server is online. The initialization process took 13426ms
[Espresso] Starting the session
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8300/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","app":"/Users/users/Downloads/test.apk","appPackage":"in.packagename","appWaitActivity":"in.activityname","appWaitDuration":10000000000000,"espressoBuildConfig":"{\"additionalAppDependencies\":[\"org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10\"]}","espressoServerLaunchTimeout":1000000000,"forceEspressoRebuild":true,"showGradleLog":true,"autoGrantPermissions":true,"automationName":"Espresso","noSign":true,"systemPort":8300},"platformName":"android","app":"/Users/user/Downloads/test.apk","appPackage":"in.package","appWaitActivity":"in.SplashActivity","appWaitDuration":10000000000000,"espressoBuildConfig":"{\"additionalAppDependencies\":[\"org.jet...
(node:1742) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[debug] [Espresso] [Instrumentation] Process crashed while executing startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
[debug] [Espresso] java.lang.NoSuchMethodError: No virtual method getSetViewConfiguration()Lkotlin/jvm/functions/Function2; in class Landroidx/compose/ui/node/ComposeUiNode$Companion; or its super classes (declaration of 'androidx.compose.ui.node.ComposeUiNode$Companion' appears in /data/app/~~Ry3nYBjeS20BpGWxB11ilA==/io.appium.espressoserver.test-YuWn_0q021WIEj1tmU-cIg==/base.apk)
[debug] [Espresso] 	at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:288)
[debug] [Espresso] 	at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:254)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:251)
[debug] [Espresso] 	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:110)
[debug] [Espresso] 	at company.library.composeui.theme.ThemeKt$CompanyAppTheme$1$1$1$1.invoke(Theme.kt:152)
[debug] [Espresso] 	at company.library.composeui.theme.ThemeKt$CompanyhatAppTheme$1$1$1$1.invoke(Theme.kt:151)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:252)
[debug] [Espresso] 	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
[debug] [Espresso] 	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:72)
[debug] [Espresso] 	at company.library.composeui.theme.ThemeKt$companyAppTheme$1$1$1.invoke(Theme.kt:149)
[debug] [Espresso] 	at company.library.composeui.theme.ThemeKt$companyAppTheme$1$1$1.invoke(Theme.kt:148)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at company.library.composeui.theme.ThemeKt$companyAppTheme$1$1.invoke(Theme.kt:142)
[debug] [Espresso] 	at company.library.composeui.theme.ThemeKt$companyAppTheme$1$1.invoke(Theme.kt:141)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at company.library.composeui.theme.TypeKt.ProvidecompanyTypography(Type.kt:446)
[debug] [Espresso] 	at company.library.composeui.theme.ThemeKt$companyAppTheme$1.invoke(Theme.kt:141)
[debug] [Espresso] 	at company.library.composeui.theme.ThemeKt$companyAppTheme$1.invoke(Theme.kt:140)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at company.library.composeui.theme.ColorKt.ProvidecompanyColors(Color.kt:335)
[debug] [Espresso] 	at company.library.composeui.theme.ThemeKt.companyAppTheme-Sj8uqqQ(Theme.kt:140)
[debug] [Espresso] 	at company.library.composeui.common.BaseViewKt$BaseView$4$1.invoke(BaseView.kt:31)
[debug] [Espresso] 	at company.library.composeui.common.BaseViewKt$BaseView$4$1.invoke(BaseView.kt:30)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at com.google.accompanist.insets.WindowInsetsKt$ProvideWindowInsets$2.invoke(WindowInsets.kt:362)
[debug] [Espresso] 	at com.google.accompanist.insets.WindowInsetsKt$ProvideWindowInsets$2.invoke(WindowInsets.kt:361)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at com.google.accompanist.insets.WindowInsetsKt.ProvideWindowInsets(WindowInsets.kt:361)
[debug] [Espresso] 	at company.library.composeui.common.BaseViewKt$BaseView$4.invoke(BaseView.kt:30)
[debug] [Espresso] 	at company.library.composeui.common.BaseViewKt$BaseView$4.invoke(BaseView.kt:29)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at company.library.composeui.common.BaseViewKt.BaseView-BAq54LU(BaseView.kt:20)
[debug] [Espresso] 	at in.company.login.language.LanguageSelectActivity$onCreate$2$1.invoke(LanguageSelectActivity.kt:89)
[debug] [Espresso] 	at in.company.login.language.LanguageSelectActivity$onCreate$2$1.invoke(LanguageSelectActivity.kt:88)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at in.company.login.language.LanguageSelectActivity$onCreate$2.invoke(LanguageSelectActivity.kt:88)
[debug] [Espresso] 	at in.company.login.language.LanguageSelectActivity$onCreate$2.invoke(LanguageSelectActivity.kt:87)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:384)
[debug] [Espresso] 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:228)
[debug] [Espresso] 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:227)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:148)
[debug] [Espresso] 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:114)
[debug] [Espresso] 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:113)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:106)
[debug] [Espresso] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:162)
[debug] [Espresso] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:161)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
[debug] [Espresso] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.andr
[debug] [Espresso] [Instrumentation] oid.kt:161)
[debug] [Espresso] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:144)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [Espresso] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [Espresso] 	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3330)
[debug] [Espresso] 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2577)
[debug] [Espresso] 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2573)
[debug] [Espresso] 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:540)
[debug] [Espresso] 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2566)
[debug] [Espresso] 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:2517)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:476)
[debug] [Espresso] 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:727)
[debug] [Espresso] 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:432)
[debug] [Espresso] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:144)
[debug] [Espresso] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:135)
[debug] [Espresso] 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:727)
[debug] [Espresso] 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:135)
[debug] [Espresso] 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:187)
[debug] [Espresso] 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
[debug] [Espresso] 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
[debug] [Espresso] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
[debug] [Espresso] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:135)
[debug] [Espresso] 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:814)
[debug] [Espresso] 	at android.view.View.dispatchAttachedToWindow(View.java:20820)
[debug] [Espresso] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3566)
[debug] [Espresso] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3573)
[debug] [Espresso] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3573)
[debug] [Espresso] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3573)
[debug] [Espresso] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3573)
[debug] [Espresso] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3573)
[debug] [Espresso] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3573)
[debug] [Espresso] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2601)
[debug] [Espresso] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2129)
[debug] [Espresso] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8603)
[debug] [Espresso] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
[debug] [Espresso] 	at android.view.Choreographer.doCallbacks(Choreographer.java:799)
[debug] [Espresso] 	at android.view.Choreographer.doFrame(Choreographer.java:734)
[debug] [Espresso] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
[debug] [Espresso] 	at android.os.Handler.handleCallback(Handler.java:938)
[debug] [Espresso] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[debug] [Espresso] 	at android.os.Looper.loop(Looper.java:236)
[debug] [Espresso] 	at android.app.ActivityThread.main(ActivityThread.java:7864)
[debug] [Espresso] 	at java.lang.reflect.Method.invoke(Native Method)
[debug] [Espresso] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
[debug] [Espresso] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
[WD Proxy] socket hang up
[debug] [Espresso] Deleting espresso session
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell am force-stop in.company.co'
[debug] [Espresso] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [Espresso] INSTRUMENTATION_CODE: 0
[debug] [Logcat] Stopping logcat capture
[debug] [Logcat] Logcat already stopped
[Espresso] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [ADB] Removing forwarded port socket connection: 8300 
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 forward --remove tcp:8300'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1651033336017 (09:52:16 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: A new session could not be created. Details: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[debug] [W3C] UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[debug] [W3C]     at EspressoProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[debug] [W3C]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [W3C]     at EspressoRunner.startSession (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:309:5)
[debug] [W3C]     at EspressoDriver.startEspressoSession (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:320:5)
[debug] [W3C]     at EspressoDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:190:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:35)

**Comment by rockstarrocks2020** [comment]
**gradle Cache clean is throwing these issues again:**


org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: A new session could not be created. Details: Unable to build Espresso server - Process ended with exitcode 1 (cmd: './gradlew -PappiumTargetPackage\=in.company.app\:assembleAndroidTest')
Gradle error message:

[STDERR] FAILURE: Build failed with an exception.,
[STDERR] ,
[STDERR] * What went wrong:,
[STDERR] Execution failed for task ':app:mergeDebugResources'.,
[STDERR] > A build operation failed.,
[STDERR]       java.nio.file.NoSuchFileException: /Users/user/.gradle/caches/transforms-3/b1635e528e182f0463054d009f5bb369/results.bin,
[STDERR]    > java.nio.file.NoSuchFileException: /Users/user/.gradle/caches/transforms-3/b1635e528e182f0463054d009f5bb369/results.bin,
[STDERR] ,
[STDERR] * Try:,
[STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
[STDERR] ,
[STDERR] * Get more help at https://help.gradle.org,
[STDERR] ,
[STDERR] BUILD FAILED in 1s,
[STDOUT] 4 actionable tasks: 1 executed, 3 from cache. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'user-MacBook-Pro', ip: 'fd01:0:0:0:14d0:b724:37db:ada0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.0', java.version: '11.0.14'
Driver info: driver.version: AndroidDriver
remote stacktrace: Error: Unable to build Espresso server - Process ended with exitcode 1 (cmd: './gradlew -PappiumTargetPackage\=in.company.app\:assembleAndroidTest')
Gradle error message:

[STDERR] FAILURE: Build failed with an exception.,
[STDERR] ,
[STDERR] * What went wrong:,
[STDERR] Execution failed for task ':app:mergeDebugResources'.,
[STDERR] > A build operation failed.,
[STDERR]       java.nio.file.NoSuchFileException: /Users/user/.gradle/caches/transforms-3/b1635e528e182f0463054d009f5bb369/results.bin,
[STDERR]    > java.nio.file.NoSuchFileException: /Users/user/.gradle/caches/transforms-3/b1635e528e182f0463054d009f5bb369/results.bin,
[STDERR] ,
[STDERR] * Try:,
[STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
[STDERR] ,
[STDERR] * Get more help at https://help.gradle.org,
[STDERR] ,
[STDERR] BUILD FAILED in 1s,
[STDOUT] 4 actionable tasks: 1 executed, 3 from cache. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
    at Object.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
    at ServerBuilder.runBuildProcess (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/server-builder.js:191:11)
    at ServerBuilder.build (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/server-builder.js:72:5)
    at EspressoRunner.buildNewModServer (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:188:5)
    at EspressoRunner.installTestApk (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:146:7)
    at EspressoDriver.initAUT (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:435:7)
    at EspressoDriver.startEspressoSession (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:298:5)
    at EspressoDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:190:7)
    at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:35)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'user-MacBook-Pro', ip: 'fd01:0:0:0:14d0:b724:37db:ada0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.0', java.version: '11.0.14'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:216)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:225)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:99)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:97)
	at co.company.utils.TestSetUpFactory.launchApplication(TestSetUpFactory.java:410)
	at co.company.utils.TestSetUp.beforeClass(TestSetUp.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:193)
	... 36 more
Caused by: org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: Unable to build Espresso server - Process ended with exitcode 1 (cmd: './gradlew -PappiumTargetPackage\=in.company.app\:assembleAndroidTest')
Gradle error message:

[STDERR] FAILURE: Build failed with an exception.,
[STDERR] ,
[STDERR] * What went wrong:,
[STDERR] Execution failed for task ':app:mergeDebugResources'.,
[STDERR] > A build operation failed.,
[STDERR]       java.nio.file.NoSuchFileException: /Users/user/.gradle/caches/transforms-3/b1635e528e182f0463054d009f5bb369/results.bin,
[STDERR]    > java.nio.file.NoSuchFileException: /Users/user/.gradle/caches/transforms-3/b1635e528e182f0463054d009f5bb369/results.bin,
[STDERR] ,
[STDERR] * Try:,
[STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
[STDERR] ,
[STDERR] * Get more help at https://help.gradle.org,
[STDERR] ,
[STDERR] BUILD FAILED in 1s,
[STDOUT] 4 actionable tasks: 1 executed, 3 from cache. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'user-MacBook-Pro', ip: 'fd01:0:0:0:14d0:b724:37db:ada0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.0', java.version: '11.0.14'
Driver info: driver.version: AndroidDriver
remote stacktrace: Error: Unable to build Espresso server - Process ended with exitcode 1 (cmd: './gradlew -PappiumTargetPackage\=in.company app\:assembleAndroidTest')
Gradle error message:

[STDERR] FAILURE: Build failed with an exception.,
[STDERR] ,
[STDERR] * What went wrong:,
[STDERR] Execution failed for task ':app:mergeDebugResources'.,
[STDERR] > A build operation failed.,
[STDERR]       java.nio.file.NoSuchFileException: /Users/user/.gradle/caches/transforms-3/b1635e528e182f0463054d009f5bb369/results.bin,
[STDERR]    > java.nio.file.NoSuchFileException: /Users/user/.gradle/caches/transforms-3/b1635e528e182f0463054d009f5bb369/results.bin,
[STDERR] ,
[STDERR] * Try:,
[STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
[STDERR] ,
[STDERR] * Get more help at https://help.gradle.org,
[STDERR] ,
[STDERR] BUILD FAILED in 1s,
[STDOUT] 4 actionable tasks: 1 executed, 3 from cache. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
    at Object.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
    at ServerBuilder.runBuildProcess (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/server-builder.js:191:11)
    at ServerBuilder.build (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/server-builder.js:72:5)
    at EspressoRunner.buildNewModServer (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:188:5)
    at EspressoRunner.installTestApk (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:146:7)
    at EspressoDriver.initAUT (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:435:7)
    at EspressoDriver.startEspressoSession (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:298:5)
    at EspressoDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:190:7)
    at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:35)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 41 more
